version = 0.1

[default.deploy.parameters]
stack_name = "sqs-jobs-api"
s3_prefix = "sqs-jobs-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\" EnqueueLambdaArn=\"arn:aws:lambda:us-east-1:815254799150:function:compare-resume-id\" StatusLambdaArn=\"arn:aws:lambda:us-east-1:815254799150:function:get-job-processing-status\""
image_repositories = []
