version = 0.1

[default.deploy.parameters]
stack_name = "trenddev-api"
s3_prefix = "trenddev-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\" JobPostingsFnArn=\"arn:aws:lambda:us-east-1:815254799150:function:get-job-postings-paginated\" JobStatsFnArn=\"arn:aws:lambda:us-east-1:815254799150:function:get-job-postings-stats\" TrendsTechnologyFnArn=\"\" TrendsRegionFnArn=\"\" TrendsSkillFnArn=\"arn:aws:lambda:us-east-1:815254799150:function:get-skill-trends\""
image_repositories = []
