version = 0.1

[default.deploy.parameters]
stack_name = "ingest-jobs"
s3_bucket = "sam-artifacts-815254799150-us-east-1"
resolve_s3 = false
s3_prefix = "ingest-jobs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JobsTableName=\"job-postings\" ArchiveBucketName=\"job-postings-bucket-cstannahill\""
image_repositories = []
